apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-products
  labels:
  keel.sh/policy: force
    keel.sh/match-tag: "true"
    keel.sh/trigger: poll
  annotations:
    keel.sh/pollSchedule: @every 1m
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: svc-products
  template:
    metadata:
      labels:
        app: svc-products
    spec:
      containers:
        - image: index.docker.io/ruslanbyondxr/svc-products:b41c631
          name: svc-products
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3333
