apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-products
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: svc-products
  template:
    metadata:
      labels:
        app: svc-products
    spec:
      containers:
        - image: index.docker.io/ruslanbyondxr/svc-products:2cbbb28
          name: svc-products
          imagePullPolicy: Always
          ports:
            - containerPort: 3333
