apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: kustomize-

resources:
- deployment.yaml
- service.yaml
images:
- name: index.docker.io/ruslanbyondxr/svc-cart
  newTag: dc2f840
- name: index.docker.io/ruslanbyondxr/svc-products
  newTag: 15e7c7e
- name: index.docker.io/ruslanbyondxr/svc-user
  newTag: 15e7c7e
