
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: svc-products
  name: svc-products
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svc-products
  template:
    metadata:
      labels:
        app: svc-products
    spec:
      containers:
        - image: index.docker.io/ruslanbyondxr/svc-products
          name: svc-products