apiVersion: v1
kind: Service
metadata:
  labels:
    app: svc-products
  name: svc-products
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 3333
  selector:
    app: svc-products
  type: NodePort